### ISSUE TITLE
How can I use this with nestJs?

### ISSUE THREAD

**Issue by Anas2001** [GO-DIE/mongoose-transaction-decorator#1]

**Comment by kasir-barati** [comment]
Some notes on this issue:

1. Its applications are very limited. You cannot decorate your service layer (e.g. [`productService`](https://github.com/kasir-barati/nestjs-materials/blob/main/mongoose/transactions/src/product/product.service.ts#L13)) method with this decorator. It works only when we have our model defined as a prop (something we usually do in [our repository layer](https://github.com/kasir-barati/nestjs-materials/blob/main/mongoose/transactions/src/database/abstract.repository.ts#L19)).
2. Even if annotate my repository method with it is gonna throw at me this unfathomable error message :sweat_drops: 

    ```cmd
    Cannot read properties of undefined (reading 'get')
    TypeError: Cannot read properties of undefined (reading 'get')
              at ALS.get (/app/node_modules/.pnpm/mongoose-transaction-decorator@1.0.1_@aws-sdk+client-sso-oidc@3.645.0_@aws-sdk+client-sts@3.645.0_/node_modules/mongoose-transaction-decorator/build/als.js:36:28)
              at model.Query.preCb (/app/node_modules/.pnpm/mongoose-transaction-decorator@1.0.1_@aws-sdk+client-sso-oidc@3.645.0_@aws-sdk+client-sts@3.645.0_/node_modules/mongoose-transaction-decorator/build/plugin.js:43:25)
              at callMiddlewareFunction (/app/node_modules/.pnpm/kareem@2.6.3/node_modules/kareem/index.js:628:27)
              at next (/app/node_modules/.pnpm/kareem@2.6.3/node_modules/kareem/index.js:93:7)
              at Kareem.execPre (/app/node_modules/.pnpm/kareem@2.6.3/node_modules/kareem/index.js:122:8)
              at /app/node_modules/.pnpm/mongoose@8.6.1_@aws-sdk+credential-providers@3.645.0_@aws-sdk+client-sso-oidc@3.645.0_@aws-sd_cqtkufkhd4lmqnrkavp3yjb22m/node_modules/mongoose/lib/query.js:4498:28
              at new Promise (<anonymous>)
              at _executePreHooks (/app/node_modules/.pnpm/mongoose@8.6.1_@aws-sdk+credential-providers@3.645.0_@aws-sdk+client-sso-oidc@3.645.0_@aws-sd_cqtkufkhd4lmqnrkavp3yjb22m/node_modules/mongoose/lib/query.js:4497:10)
              at model.Query.exec (/app/node_modules/.pnpm/mongoose@8.6.1_@aws-sdk+credential-providers@3.645.0_@aws-sdk+client-sso-oidc@3.645.0_@aws-sd_cqtkufkhd4lmqnrkavp3yjb22m/node_modules/mongoose/lib/query.js:4411:11)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    ```

See more here in this repo: https://github.com/kasir-barati/nestjs-materials/tree/main/mongoose/transactions

> [!NOTE]
> Read the [`README.md`](https://github.com/kasir-barati/nestjs-materials/tree/main/mongoose/transactions#how-to-run-it) for learning how to run it.

**Comment by kasir-barati** [comment]
I guess this lib is being abandoned :thinking:.
